"""
Example: How to load and use a JSON configuration with Voyager.

This demonstrates how to manually load a configuration file generated by the GUI
and use it to instantiate Voyager.
"""

import json
from voyager import Voyager


def load_voyager_from_config(config_file="voyager_config_example.json", openai_api_key=None, azure_login=None):
    """
    Load Voyager configuration from a JSON file and instantiate Voyager.

    Args:
        config_file: Path to the JSON configuration file
        openai_api_key: Your OpenAI API key (will override config if provided)
        azure_login: Azure login configuration (will override config if provided)

    Returns:
        Voyager instance
    """
    with open(config_file, 'r') as f:
        config = json.load(f)

    # Use provided credentials or require them to be set
    if openai_api_key is None:
        openai_api_key = input("Enter your OpenAI API key: ")

    if azure_login is None:
        print("\nAzure Login Configuration:")
        azure_login = {
            "client_id": input("Client ID: "),
            "redirect_url": input("Redirect URL (default: https://127.0.0.1/auth-response): ") or "https://127.0.0.1/auth-response",
            "secret_value": input("Secret value (optional, press Enter to skip): ") or None,
            "version": input("Version (default: fabric-loader-0.14.18-1.19): ") or "fabric-loader-0.14.18-1.19",
        }

    # Create Voyager with the loaded configuration
    voyager = Voyager(
        azure_login=azure_login,
        openai_api_key=openai_api_key,
        action_agent_model_name=config["action_agent"]["model"],
        action_agent_temperature=config["action_agent"]["temperature"],
        curriculum_agent_model_name=config["curriculum_agent"]["model"],
        curriculum_agent_temperature=config["curriculum_agent"]["temperature"],
        curriculum_agent_qa_model_name=config["curriculum_agent"]["qa_model"],
        curriculum_agent_qa_temperature=config["curriculum_agent"]["qa_temperature"],
        critic_agent_model_name=config["critic_agent"]["model"],
        critic_agent_temperature=config["critic_agent"]["temperature"],
        skill_manager_model_name=config["skill_manager"]["model"],
        skill_manager_temperature=config["skill_manager"]["temperature"],
    )

    # Display configuration summary
    print("\n" + "="*60)
    print("Voyager Configuration Loaded")
    print("="*60)
    print(f"Action Agent:        {config['action_agent']['model']} (temp={config['action_agent']['temperature']})")
    print(f"Curriculum Agent:    {config['curriculum_agent']['model']} (temp={config['curriculum_agent']['temperature']})")
    print(f"Curriculum QA:        {config['curriculum_agent']['qa_model']} (temp={config['curriculum_agent']['qa_temperature']})")
    print(f"Critic Agent:         {config['critic_agent']['model']} (temp={config['critic_agent']['temperature']})")
    print(f"Skill Manager:        {config['skill_manager']['model']} (temp={config['skill_manager']['temperature']})")
    print(f"Reasoning Effort:     {config['reasoning_effort']}")
    print(f"Verbosity:            {config['verbosity']}")
    print(f"Store:                {config['store']}")
    print("="*60 + "\n")

    return voyager, config.get('chat_completions_options', {})


if __name__ == "__main__":
    # Example usage
    voyager, chat_options = load_voyager_from_config()

    # Start learning (uncomment to actually run)
    # voyager.learn()

    # Or run a specific task
    # task = "Craft a diamond pickaxe"
    # sub_goals = voyager.decompose_task(task)
    # voyager.inference(sub_goals=sub_goals)
