"""
Example: How to load and use a JSON configuration with Voyager.

This demonstrates how to manually load a configuration file generated by the GUI
and use it to instantiate Voyager.
"""

import json
from voyager import Voyager


def load_voyager_from_config(
    config_file="voyager_config_example.json", openai_api_key=None, mc_port=None
):
    """Load Voyager configuration from a JSON file and instantiate Voyager.

    The GUI can produce multiple config formats (older Tkinter format and the newer
    PyQt6 format). This loader supports both.

    Args:
        config_file: Path to the JSON configuration file
        openai_api_key: Your OpenAI API key (will override config if provided)
        mc_port: Minecraft in-game port (will override config if provided)

    Returns:
        (Voyager instance, chat_completions_options dict)
    """

    with open(config_file, "r") as f:
        config = json.load(f)

    settings = config.get("settings") if isinstance(config.get("settings"), dict) else {}
    old_settings = (
        config.get("old_settings") if isinstance(config.get("old_settings"), dict) else {}
    )

    reasoning_effort = settings.get("reasoning_effort", config.get("reasoning_effort"))
    verbosity = settings.get("verbosity", config.get("verbosity"))

    store = settings.get("store")
    if store is None:
        store = old_settings.get("store")
    if store is None:
        store = config.get("store")

    def _to_bool(v):
        if isinstance(v, bool):
            return v
        if isinstance(v, str):
            return v.strip().lower() == "true"
        return bool(v)

    chat_completions_options = {}
    if store is not None:
        chat_completions_options["store"] = _to_bool(store)
    if reasoning_effort:
        chat_completions_options["reasoning_effort"] = reasoning_effort
    if verbosity:
        chat_completions_options["verbosity"] = verbosity

    if old_settings.get("top_p") is not None:
        chat_completions_options["top_p"] = old_settings["top_p"]
    if old_settings.get("max_tokens") is not None:
        chat_completions_options["max_tokens"] = old_settings["max_tokens"]

    # Use provided credentials or require them to be set
    if openai_api_key is None:
        openai_api_key = input("Enter your OpenAI API key: ")

    if mc_port is None:
        print("\nMinecraft Configuration:")
        mc_port = int(input("Enter Minecraft in-game port: "))

    # Create Voyager with the loaded configuration
    voyager = Voyager(
        mc_port=mc_port,
        openai_api_key=openai_api_key,
        action_agent_model_name=config["action_agent"]["model"],
        action_agent_temperature=config["action_agent"]["temperature"],
        curriculum_agent_model_name=config["curriculum_agent"]["model"],
        curriculum_agent_temperature=config["curriculum_agent"]["temperature"],
        curriculum_agent_qa_model_name=config["curriculum_agent"]["qa_model"],
        curriculum_agent_qa_temperature=config["curriculum_agent"]["qa_temperature"],
        critic_agent_model_name=config["critic_agent"]["model"],
        critic_agent_temperature=config["critic_agent"]["temperature"],
        skill_manager_model_name=config["skill_manager"]["model"],
        skill_manager_temperature=config["skill_manager"]["temperature"],
    )

    # Display configuration summary
    print("\n" + "=" * 60)
    print("Voyager Configuration Loaded")
    print("=" * 60)
    print(
        f"Action Agent:        {config['action_agent']['model']} (temp={config['action_agent']['temperature']})"
    )
    print(
        f"Curriculum Agent:    {config['curriculum_agent']['model']} (temp={config['curriculum_agent']['temperature']})"
    )
    print(
        f"Curriculum QA:       {config['curriculum_agent']['qa_model']} (temp={config['curriculum_agent']['qa_temperature']})"
    )
    print(
        f"Critic Agent:        {config['critic_agent']['model']} (temp={config['critic_agent']['temperature']})"
    )
    print(
        f"Skill Manager:       {config['skill_manager']['model']} (temp={config['skill_manager']['temperature']})"
    )

    if reasoning_effort is not None:
        print(f"Reasoning Effort:     {reasoning_effort}")
    if verbosity is not None:
        print(f"Verbosity:            {verbosity}")
    if store is not None:
        print(f"Store:                {store}")

    if old_settings.get("top_p") is not None:
        print(f"Top-p:               {old_settings['top_p']}")
    if old_settings.get("max_tokens") is not None:
        print(f"Max tokens:          {old_settings['max_tokens']}")

    print("=" * 60 + "\n")

    return voyager, chat_completions_options


if __name__ == "__main__":
    # Example usage
    voyager, chat_options = load_voyager_from_config()

    # Start learning (uncomment to actually run)
    # voyager.learn()

    # Or run a specific task
    # task = "Craft a diamond pickaxe"
    # sub_goals = voyager.decompose_task(task)
    # voyager.inference(sub_goals=sub_goals)
